routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'as'      => 'home',
    'uses'    => 'site\SiteController@index'
]);


Route::group(['prefix' => 'manage', 'middleware' => 'role:superadministrator|administrator'], function () {
    Route::get('/', 'cms\AdminController@get_index')->name('site');
    Route::resource('/users', 'cms\UserController');
    Route::resource('/posts', 'cms\PostController');
    Route::resource('/pages', 'cms\PageController');    
    Route::resource('/contents', 'cms\ContentController');        
    Route::resource('/describing', 'cms\DescribingController');

    //CONTENS
    Route::resource('/banners', 'cms\BannerController');
    Route::resource('/brands', 'cms\BrandController');    
    Route::resource('/generic', 'cms\GenericController');
    Route::resource('/forum', 'cms\ForumController');
    Route::resource('/packets', 'cms\PacketController');    
    
    Route::get('/menu', 'cms\AdminController@getmenu')->name('menu');
    Route::post('/menu', 'cms\AdminController@postmenu');
    Route::get('/settings', 'cms\AdminController@get_settings')->name('settings');
    Route::post('/settings', 'cms\AdminController@post_settings');
    Route::post('/ajax', 'cms\AjaxController@post');
    Route::get('/media', function(){ return view('cms.media.index');})->name('media');
    Route::get('/media/files', function(){ return view('cms.media.files');})->name('media-files');

    // Other Link
    Route::get('posts/delete/{post_id}', ['uses' => 'cms\PostController@delete', 'as' => 'delete-post']);
    Route::get('banners/delete/{banner_id}', ['uses' => 'cms\BannerController@delete', 'as' => 'delete-banner']);
    Route::get('brands/delete/{brand_id}', ['uses' => 'cms\BrandController@delete', 'as' => 'delete-brand']);
    
    
    Route::get('/datatable/posts', ['uses' => 'cms\PostController@datatable', 'as' => 'posts.datatable']);
    Route::get('/datatable/banners', ['uses' => 'cms\BannerController@bannerDatatable', 'as' => 'banner.datatable']);
    Route::get('/datatable/brands', ['uses' => 'cms\BrandController@brandDatatable', 'as' => 'brand.datatable']);    
    Route::get('/datatable/generic', ['uses' => 'cms\GenericController@genericDatatable', 'as' => 'generic.datatable']);
    Route::get('/datatable/forum', ['uses' => 'cms\ForumController@forumDatatable', 'as' => 'forum.datatable']);
    Route::get('/datatable/packets', ['uses' => 'cms\PacketController@packetDatatable', 'as' => 'packet.datatable']);    

});
Auth::routes();


// Catch all page controller (place at the very bottom)
if (!Request::is('laravel-*') && !Request::is('photos/')){

    //Static Pages
    Route::get('forum', 'site\ForumController@index');
    Route::get('forum/{slug}', 'site\ForumController@show');    
    Route::get('iletisim', 'site\SiteController@contact');
    Route::get('blog', 'site\BlogController@index');
    Route::get('blog/{slug}', 'site\BlogController@show');
    Route::get('blog/{slug}/amp', 'site\BlogController@amp');
    Route::get('/sitemap', 'site\SitemapController@index');

    //Forms
    Route::get('form/{slug1}', 'site\FormController@index');

    Route::post('form', 'site\FormController@send')->name('form-send');

    //All Urls
    Route::get('{slug1}/{slug2?}/{slug3?}/{slug4?}', ['uses' => 'site\SiteController@getPage'])->where('slug', '([A-Za-z0-9\-\/]+)');
}

Route::get('/laravel-clear', function () {   
    echo "Cache temizlendi!";
});

app/Content.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Contents_Detail;
use App\User;
class Content extends Model
{
    use SoftDeletes;
    protected $table = 'contents';
    protected $fillable = ['title','slug','rank', 'published_at', 'user_id','excerpt','content','type','status'];
    protected $dates = ['deleted_at'];
    protected $softDelete = true;

    public function details(){
        return $this->hasMany('App\Contents_Detail');

    }

    public function user(){
        return $this->hasOne('App\User','id','user_id');
    }

    // public function children()
    // {
    //     return $this->hasMany('App\Post','parent_id');
    // }
}

app/Http/Controllers/cms/ContentController.php
<?php

namespace App\Http\Controllers\cms;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Content;
use Datatables;

class ContentController extends Controller
{
    public function index(){
        return view('cms.contents.index');
    }
    public function create(){
        $content=Content::where('parent_id','0')->pluck('title','id');
        $content=collect(['' => 'Seçiniz'] + $category->all());
        
        return view('cms.contents.create')->with('content',$content);
    }

    public function bannerIndex(){
        return view('cms.contents.banners.index');
    }






}

resources/views/cms/contents/generic_content/create.blade.php
 @extends('cms.app') @section('title') Ortak İçerik Ekle @endsection @section('content')
<div class="content sm-gutter">
	<!-- START CONTAINER FLUID -->
	<div class="jumbotron" data-pages="parallax">
		<div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
			<div class="inner" style="transform: translateY(0px); opacity: 1;">
				<h4 class="page-title">@yield('title')</h4>
			</div>
		</div>
	</div>
	<div class="container-fluid container-fixed-lg">
		<div class="row">
			<form data-js="slug summernote" action="{{route('generic.store')}}" method="POST" id="form" enctype="multipart/form-data">
				{{ csrf_field() }}
				<div class="col-sm-8 col-md-9 no-padding">
						<input type="hidden" name="lang" value="tr">
				<input type="hidden" name="type" value="generic">
					@if ($errors->any())
					<div class="alert alert-danger">
						<ul>
							@foreach ($errors->all() as $error)
							<li>{{ $error }}</li>
							@endforeach
						</ul>
					</div>
					@endif

					<div class="col-sm-12">
						<div class="form-group form-group-default required">
							<label>Başlık</label>
							<input type="text" class="form-control" name="title" required value="">
						</div>
					</div>
					<div class="col-sm-12">
						<div class="form-group form-group-default input-group required">
						<span class="input-group-addon">
							<label>Kısakod:</label>
						</span>
							<label>Url</label>
							<input type="text" class="form-control" name="slug" placeholder="" required
								   value="">
						</div>
					</div>
					<div class="col-sm-12">
						<h5>İçerik</h5>
						<div class="summernote-wrapper">
							<textarea id="summernote-editor" name="content"></textarea>

						</div>
					</div>
					<div class="col-sm-12">
						<div class="form-group form-group-default required">
							<label>Açıklama</label>
							<textarea style="min-height:90px" rows="10" cols="10" class="form-control required" name="excerpt"></textarea>
						</div>
					</div>
				</div>
				<div class="col-sm-4 col-md-3">
					<div class="row">
						<div class="card share">							
							<div class="card-description">
								@if (Auth::user()->hasRole('superadministrator'))<button class="btn btn-warning pull-left" type="submit" name="status" value="draft">Taslak</button>@endif
								<button type="submit" class="btn btn-primary pull-right" name="status" value="published">Yayınla</button>

							</div>

						</div>
					</div>
				</div>

			</form>

		</div>
	</div>
</div>
@endsection @section('css') @section('js')
<script src="/cms/js/form.js"></script>

<script>
	{!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/lfm.js')) !!}
    var route_prefix = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";
    $('#lfm').filemanager('image', {prefix: route_prefix});

</script>
@endsection

resources/views/cms/contents/generic_content/edit.blade.php
@extends('cms.app') 
@section('title') Ortak İçerik Düzenle
@endsection
 
@section('content')
<div class="content sm-gutter">
    <!-- START CONTAINER FLUID -->
    <div class="jumbotron" data-pages="parallax">
        <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
            <div class="inner" style="transform: translateY(0px); opacity: 1;">
                <h4 class="page-title">@yield('title')</h4>
            </div>
        </div>
    </div>
    <div class="container-fluid container-fixed-lg">
        <div class="row">
            <form data-js="summernote" action="{{route('generic.update',$generic->id)}}" method="POST" id="form" enctype="multipart/form-data">
                {{ csrf_field() }} {{ method_field('PATCH') }}
                <div class="col-sm-8 col-md-9 no-padding">
                    <input type="hidden" name="lang" value="tr">
                    <input type="hidden" name="type" value="generic"> @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <div class="col-sm-12">
                        <div class="form-group form-group-default required">
                            <label>Başlık</label>
                            <input type="text" class="form-control" readonly name="title" required value="{{$generic->title}}">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group form-group-default required">
                            <label>Kısa Kod</label>
                            <input type="text" class="form-control required" readonly name="slug" placeholder="" required value="{{$generic->slug}}">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <h5>İçerik</h5>
                        <div class="summernote-wrapper required">
                            <textarea id="summernote-editor" class="required" name="content">{{$generic->content}}</textarea>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group form-group-default">
                            <label>Açıklama</label>
                            <textarea style="min-height:90px" rows="10" cols="10" class="form-control" name="excerpt">{{$generic->excerpt}}</textarea>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-md-3">
                    <div class="row">
                        <div class="card share">
                            <div class="card-header clearfix">
                                <div class="user-pic">
                                    <img alt="Profile Image" width="33" height="33" data-src-retina="/cms/img/profiles/avatar.jpg" data-src="/cms/img/profiles/avatar.jpg"
                                        src="/cms/img/profiles/avatar.jpg">
                                </div>
                                <h5>{{$generic->user->name}}</h5>
                                <h6>{{__('cms.'.$generic->status)}}
                                    <span class="location semi-bold">
                                        <i class="fa fa-clock-o"></i> {{$generic->published_at}}</span>
                                </h6>
                            </div>
                            <div class="card-description">
                                @if (Auth::user()->hasRole('superadministrator'))
                                <a class="delete-btn btn btn-danger pull-left" style="margin-right:10px;" href="{{ URL::route('generic.destroy',$generic->id) }}">Sil</a>                                
                                <button class="btn btn-warning pull-left" type="submit" name="status" value="draft">Taslak</button>@endif
                                <button type="submit" class="btn btn-primary pull-right" name="status" value="published">Düzenle</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
 
@section('css')
@endsection
 
@section('js')
<script src="/cms/js/form.js"></script>

<script>
    {!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/lfm.js')) !!}
            var route_prefix = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";
            $('#lfm').filemanager('image', {prefix: route_prefix});
</script>
@endsection

resources/views/cms/contents/generic_content/index.blade.php
@extends('cms.app')
@section('title') Ortak İçerikler @endsection
@section('secondnav')<a href="#" class="toggle-secondary-sidebar">İçerikler<span class="text-info"></span> <span class="caret"></span></a>@endsection

@section('content')
    <div class="content full-height">
        @include('_layouts.contentsidebar')
        <div class="inner-content full-height">
            <div class="jumbotron" data-pages="parallax">
                <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
                    <div class="inner" style="transform: translateY(0px); opacity: 1;">
                        <h4 class="page-title">@yield('title')</h4>
                    </div>
                    @if (Auth::user()->hasRole('superadministrator'))  
                    <div class="new-append-button ">
                            <a href="{{route('generic.create')}}" class="btn btn-primary">
                                    <i class="fa fa-plus"></i> <span>Yeni Ekle</span>
                                </a>
                        </div>
                        @endif
                </div>
            </div>            
            <div class="panel-body">
                    <table class="table table-hover demo-table-search table-responsive-block dataTable no-footer reorder" id="datatable" width="100%">
                        <thead>
                        <tr>
                            <th>Başlık</th>                            
                            <th>Tarih</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>
           </div>
        </div>
    </div>
@endsection
@section('css')

@endsection

@section('js')
    <script src="/cms/js/datatable.js"></script>
    <script>
        columns= [
            { data: 'title', name: 'title' },          
            { data: 'created_at', name: 'created_at' },
            {data: 'action', name: 'action', orderable: false, searchable: false}

        ]
        setDatatable('{!! route('generic.datatable') !!}',columns,false,"App\\Content");
    </script>
    <script>
            $('.toggle-secondary-sidebar').click(function(e) {
            e.stopPropagation();
            $('.secondary-sidebar').toggle();
            });
            $(window).resize(function() {
        
                if ($(window).width() <= 1024) {
                    $('.secondary-sidebar').hide();
        
                } else {
                    $('.secondary-sidebar').show();
                }
            });
            </script>
@endsection