routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'as'      => 'home',
    'uses'    => 'site\SiteController@index'
]);


Route::group(['prefix' => 'manage', 'middleware' => 'role:superadministrator|administrator'], function () {
    Route::get('/', 'cms\AdminController@get_index')->name('site');
    Route::resource('/users', 'cms\UserController');
    Route::resource('/posts', 'cms\PostController');
    Route::resource('/pages', 'cms\PageController');    
    Route::resource('/contents', 'cms\ContentController');        
    Route::resource('/describing', 'cms\DescribingController');

    //CONTENS
    Route::resource('/banners', 'cms\BannerController');
    Route::resource('/brands', 'cms\BrandController');    
    Route::resource('/generic', 'cms\GenericController');
    Route::resource('/forum', 'cms\ForumController');
    Route::resource('/packets', 'cms\PacketController');    
    
    Route::get('/menu', 'cms\AdminController@getmenu')->name('menu');
    Route::post('/menu', 'cms\AdminController@postmenu');
    Route::get('/settings', 'cms\AdminController@get_settings')->name('settings');
    Route::post('/settings', 'cms\AdminController@post_settings');
    Route::post('/ajax', 'cms\AjaxController@post');
    Route::get('/media', function(){ return view('cms.media.index');})->name('media');
    Route::get('/media/files', function(){ return view('cms.media.files');})->name('media-files');

    // Other Link
    Route::get('posts/delete/{post_id}', ['uses' => 'cms\PostController@delete', 'as' => 'delete-post']);
    Route::get('banners/delete/{banner_id}', ['uses' => 'cms\BannerController@delete', 'as' => 'delete-banner']);
    Route::get('brands/delete/{brand_id}', ['uses' => 'cms\BrandController@delete', 'as' => 'delete-brand']);
    
    
    Route::get('/datatable/posts', ['uses' => 'cms\PostController@datatable', 'as' => 'posts.datatable']);
    Route::get('/datatable/banners', ['uses' => 'cms\BannerController@bannerDatatable', 'as' => 'banner.datatable']);
    Route::get('/datatable/brands', ['uses' => 'cms\BrandController@brandDatatable', 'as' => 'brand.datatable']);    
    Route::get('/datatable/generic', ['uses' => 'cms\GenericController@genericDatatable', 'as' => 'generic.datatable']);
    Route::get('/datatable/forum', ['uses' => 'cms\ForumController@forumDatatable', 'as' => 'forum.datatable']);
    Route::get('/datatable/packets', ['uses' => 'cms\PacketController@packetDatatable', 'as' => 'packet.datatable']);    

});
Auth::routes();


// Catch all page controller (place at the very bottom)
if (!Request::is('laravel-*') && !Request::is('photos/')){

    //Static Pages
    Route::get('forum', 'site\ForumController@index');
    Route::get('forum/{slug}', 'site\ForumController@show');    
    Route::get('iletisim', 'site\SiteController@contact');
    Route::get('blog', 'site\BlogController@index');
    Route::get('blog/{slug}', 'site\BlogController@show');
    Route::get('blog/{slug}/amp', 'site\BlogController@amp');
    Route::get('/sitemap', 'site\SitemapController@index');

    //Forms
    Route::get('form/{slug1}', 'site\FormController@index');

    Route::post('form', 'site\FormController@send')->name('form-send');

    //All Urls
    Route::get('{slug1}/{slug2?}/{slug3?}/{slug4?}', ['uses' => 'site\SiteController@getPage'])->where('slug', '([A-Za-z0-9\-\/]+)');
}

Route::get('/laravel-clear', function () {   
    echo "Cache temizlendi!";
});

resources/views/_layouts/contentsidebar.blade.php
<nav class="secondary-sidebar padding-30">
    <ul class="main-menu">
        <li class="">
            <a class="getAltContents" data-id="banner" href="{{route('banners.index')}}">
                <span class="title"><i class=""></i>Banner</span>
            </a>
        </li>
        <li class="">
            <a class="getAltContents" data-id="generic" href="{{route('generic.index')}}">
                <span class="title"><i class=""></i>Ortak İçerikler</span>
            </a>
        </li>
        <li class="">
            <a class="getAltContents" data-id="brand" href="{{route('brands.index')}}">
                <span class="title"><i class=""></i>Şirketler</span>
            </a>
        </li>
        <li class="">
            <a class="getAltContents" data-id="forum" href="{{route('forum.index')}}">
                <span class="title"><i class=""></i>Forum</span>
            </a>
        </li>
        <li class="">
                <a class="getAltContents" data-id="insurance-packet" href="{{route('packets.index')}}">
                    <span class="title"><i class=""></i>Sigorta Paketleri</span>
                </a>
            </li>    
    </ul>
</nav>

resources/views/_layouts/loginpage.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
   <title>{{ config('app.name') }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
    <link rel="apple-touch-icon" href="/cms/pages/ico/60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/cms/ico/favicon-80x80.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/cms/ico/favicon-120x120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/cms/ico/favicon-180x180.png">
    <link rel="icon" type="image/x-icon" href="/cms/ico/favicon-80x80.png" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="LaravelBob Admin Cms" name="description" />
    <meta content="Onur Yılmaz" name="author" />

       <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link href="cms/css/bob.core.css" rel="stylesheet" />
    <link href="cms/css/app.css" rel="stylesheet" /> 

    <!--[if lte IE 9]>
        <link href="/cms/pages/css/ie9.css" rel="stylesheet" type="text/css" />
    <![endif]-->
    <script type="text/javascript">
    window.onload = function()
    {
      // fix for windows 8
      if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
        document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="/cms/pages/css/windows.chrome.fix.css" />'
    }
    </script>
  </head>
  <body class="fixed-header ">
    <div class="login-wrapper ">
      <!-- START Login Background Pic Wrapper-->
      <div class="bg-pic">
        <!-- START Background Pic-->
        <img src="/cms/img/demo/new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg" data-src="/cms/img/demo/new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg" data-src-retina="/cms/img/demo/new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg" alt="" class="lazy">
        <!-- END Background Pic-->
        <!-- START Background Caption-->
        <div class="bg-caption pull-bottom sm-pull-bottom text-white p-l-20 m-b-20">
          <h2 class="semi-bold text-white">
					Canatar Sigorta Yönetim Paneli</h2>
          <p class="small">
            © 2015-2018 Bob Agency
          </p>
        </div>
        <!-- END Background Caption-->
      </div>
      <!-- END Login Background Pic Wrapper-->
      <!-- START Login Right Container-->
       @yield('content')
    
      <!-- END Login Right Container-->
    </div>
    <!-- START OVERLAY -->
    <div class="overlay hide" data-/cms/pages="search">
      <!-- BEGIN Overlay Content !-->
      <div class="overlay-content has-results m-t-20">
        <!-- BEGIN Overlay Header !-->
        <div class="container-fluid">
          <!-- BEGIN Overlay Logo !-->
          <img class="overlay-brand" src="/cms/img/logo.png" alt="logo" data-src="/cms/img/logo.png" data-src-retina="/cms/img/logo_2x.png" width="78" height="22">
          <!-- END Overlay Logo !-->
          <!-- BEGIN Overlay Close !-->
          <a href="#" class="close-icon-light overlay-close text-black fs-16">
            <i class="pg-close"></i>
          </a>
          <!-- END Overlay Close !-->
        </div>
        <!-- END Overlay Header !-->
        <div class="container-fluid">
          <!-- BEGIN Overlay Controls !-->
          <input id="overlay-search" class="no-border overlay-search bg-transparent" placeholder="Search..." autocomplete="off" spellcheck="false">
          <br>
          <div class="inline-block">
            <div class="checkbox right">
              <input id="checkboxn" type="checkbox" value="1" checked="checked">
              <label for="checkboxn"><i class="fa fa-search"></i> Search within page</label>
            </div>
          </div>
          <div class="inline-block m-l-10">
            <p class="fs-13">Press enter to search</p>
          </div>
          <!-- END Overlay Controls !-->
        </div>
        <!-- BEGIN Overlay Search Results, This part is for demo purpose, you can add anything you like !-->
        <div class="container-fluid">
          <span>
                <strong>suggestions :</strong>
            </span>
          <span id="overlay-suggestions"></span>
          <br>
          <div class="search-results m-t-40">
            <p class="bold">/cms/pages Search Results</p>
            <div class="row">
              <div class="col-md-6">
                <!-- BEGIN Search Result Item !-->
                <div class="">
                  <!-- BEGIN Search Result Item Thumbnail !-->
                  <div class="thumbnail-wrapper d48 circular bg-success text-white inline m-t-10">
                    <div>
                      <img width="50" height="50" src="/cms/img/profiles/avatar.jpg" data-src="/cms/img/profiles/avatar.jpg" data-src-retina="/cms/img/profiles/avatar2x.jpg" alt="">
                    </div>
                  </div>
                  <!-- END Search Result Item Thumbnail !-->
                  <div class="p-l-10 inline p-t-5">
                    <h5 class="m-b-5"><span class="semi-bold result-name">ice cream</span> on /cms/pages</h5>
                    <p class="hint-text">via john smith</p>
                  </div>
                </div>
                <!-- END Search Result Item !-->
                <!-- BEGIN Search Result Item !-->
                <div class="">
                  <!-- BEGIN Search Result Item Thumbnail !-->
                  <div class="thumbnail-wrapper d48 circular bg-success text-white inline m-t-10">
                    <div>T</div>
                  </div>
                  <!-- END Search Result Item Thumbnail !-->
                  <div class="p-l-10 inline p-t-5">
                    <h5 class="m-b-5"><span class="semi-bold result-name">ice cream</span> related topics</h5>
                    <p class="hint-text">via /cms/pages</p>
                  </div>
                </div>
                <!-- END Search Result Item !-->
                <!-- BEGIN Search Result Item !-->
                <div class="">
                  <!-- BEGIN Search Result Item Thumbnail !-->
                  <div class="thumbnail-wrapper d48 circular bg-success text-white inline m-t-10">
                    <div><i class="fa fa-headphones large-text "></i>
                    </div>
                  </div>
                  <!-- END Search Result Item Thumbnail !-->
                  <div class="p-l-10 inline p-t-5">
                    <h5 class="m-b-5"><span class="semi-bold result-name">ice cream</span> music</h5>
                    <p class="hint-text">via /cms/pagesmix</p>
                  </div>
                </div>
                <!-- END Search Result Item !-->
              </div>
              <div class="col-md-6">
                <!-- BEGIN Search Result Item !-->
                <div class="">
                  <!-- BEGIN Search Result Item Thumbnail !-->
                  <div class="thumbnail-wrapper d48 circular bg-info text-white inline m-t-10">
                    <div><i class="fa fa-facebook large-text "></i>
                    </div>
                  </div>
                  <!-- END Search Result Item Thumbnail !-->
                  <div class="p-l-10 inline p-t-5">
                    <h5 class="m-b-5"><span class="semi-bold result-name">ice cream</span> on facebook</h5>
                    <p class="hint-text">via facebook</p>
                  </div>
                </div>
                <!-- END Search Result Item !-->
                <!-- BEGIN Search Result Item !-->
                <div class="">
                  <!-- BEGIN Search Result Item Thumbnail !-->
                  <div class="thumbnail-wrapper d48 circular bg-complete text-white inline m-t-10">
                    <div><i class="fa fa-twitter large-text "></i>
                    </div>
                  </div>
                  <!-- END Search Result Item Thumbnail !-->
                  <div class="p-l-10 inline p-t-5">
                    <h5 class="m-b-5">Tweats on<span class="semi-bold result-name"> ice cream</span></h5>
                    <p class="hint-text">via twitter</p>
                  </div>
                </div>
                <!-- END Search Result Item !-->
                <!-- BEGIN Search Result Item !-->
                <div class="">
                  <!-- BEGIN Search Result Item Thumbnail !-->
                  <div class="thumbnail-wrapper d48 circular text-white bg-danger inline m-t-10">
                    <div><i class="fa fa-google-plus large-text "></i>
                    </div>
                  </div>
                  <!-- END Search Result Item Thumbnail !-->
                  <div class="p-l-10 inline p-t-5">
                    <h5 class="m-b-5">Circles on<span class="semi-bold result-name"> ice cream</span></h5>
                    <p class="hint-text">via google plus</p>
                  </div>
                </div>
                <!-- END Search Result Item !-->
              </div>
            </div>
          </div>
        </div>
        <!-- END Overlay Search Results !-->
      </div>
      <!-- END Overlay Content !-->
    </div>
    <!-- END OVERLAY -->
    <!-- BEGIN VENDOR JS -->
     <script src="/cms/js/pace.js"></script>
    <script src="/cms/plugins/jquery/jquery-1.11.1.min.js" type="text/javascript"></script>

    <script src="/cms/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
    <script src="/cms/js/jquery.scrollbar.min.js"></script>
    <script src="/cms/js/bob.core.js"></script>
    <script src="/cms/js/app.js"></script>
    <script>
    $(function()
    {
      $('#form-login').validate()
    })
    </script>
  </body>
</html>

resources/views/_layouts/sidebar.blade.php
<!-- BEGIN SIDEBPANEL-->
<nav class="page-sidebar" data-pages="sidebar">
	<!-- BEGIN SIDEBAR MENU TOP TRAY CONTENT-->

	<!-- END SIDEBAR MENU TOP TRAY CONTENT-->
	<!-- BEGIN SIDEBAR MENU HEADER-->
	<div class="sidebar-header">
		<img src="/cms/img/logo_white.png" alt="logo" class="brand" data-src="/cms/img/logo_white.png" data-src-retina="/cms/img/logo_white_2x.png"
		    width="39" height="40">
		<div class="sidebar-header-controls">

			<button type="button" class="btn btn-link visible-lg-inline" data-toggle-pin="sidebar">
				<i class="fa fs-12"></i>
			</button>
		</div>
	</div>
	<!-- END SIDEBAR MENU HEADER-->
	<!-- START SIDEBAR MENU -->
	<div class="sidebar-menu">
		<!-- BEGIN SIDEBAR MENU ITEMS-->
		<ul class="menu-items">
			<li class="m-t-30 ">
				<a href="{{route('site')}}" class="detailed">
					<span class="title">Anasayfa</span>
					<span class="details"></span>
				</a>
				<span class="bg-success icon-thumbnail">
					<i class="pg-home"></i>
				</span>
			</li>
			<li class="">
				<a href="{{route('pages.index')}}" class="detailed">
					<span class="title">Sayfalar</span>
					<span class="details"></span>
				</a>
				<span class="icon-thumbnail">
					<i class="fa fa-file"></i>
				</span>
			</li>
			<li>
				<a href="javascript:;">
					<span class="title">Yazılar</span>
					<span class=" arrow"></span>
				</a>
				<span class="icon-thumbnail">
					<i class="fa fa-file"></i>
				</span>
				<ul class="sub-menu">
					<li class="">
						<a href="{{route('posts.index')}}">Tüm Yazılar</a>
						<span class="icon-thumbnail">TY</span>
					</li>
					<li class="">
						<a href="{{route('posts.create')}}">Yeni Ekle</a>
						<span class="icon-thumbnail">Y</span>
					</li>
				</ul>
			</li>
			<li class="">
				<a href="javascript:;" class="detailed">
					<span class="title">İçerikler</span>
					<span class=" arrow"></span>
				</a>
				<span class="icon-thumbnail">
					<i class="fa fa-bolt"></i>
				</span>
				<ul class="sub-menu">
					<li class="">
						<a href="{{route('banners.index')}}">Banner</a>
						<span class="icon-thumbnail">B</span>
					</li>
					<li class="">
						<a href="{{route('generic.index')}}">Ortak İçerikler</a>
						<span class="icon-thumbnail">Oİ</span>
					</li>
					<li class="">
						<a href="{{route('brands.index')}}">Şirketler</a>
						<span class="icon-thumbnail">Ş</span>
					</li>
					<li class="">
						<a href="{{route('forum.index')}}">Forum</a>
						<span class="icon-thumbnail">F</span>
					</li>
					<li class="">
							<a href="{{route('packets.index')}}">Sigorta Paketleri</a>
							<span class="icon-thumbnail">SP</span>
						</li>
				</ul>
			</li>
			<li class="">
				<a href="{{route('describing.index')}}" class="detailed">
					<span class="title">Tanımlamalar</span>
					<span class="details"></span>
				</a>
				<span class="icon-thumbnail">
					<i class="fa fa-bolt"></i>
				</span>
			</li>
			{{--
			<li class="">
				<a href="{{route('users.index')}}">
					<span class="title">Kullanıcılar</span>
				</a>
				<span class="icon-thumbnail">
					<i class="fa fa-users"></i>
				</span>
			</li> --}}
			<li class="">
				<a href="javascript:;" class="detailed">
					<span class="title">Ortam</span>
					<span class=" arrow"></span>
				</a>
				<span class="icon-thumbnail">
					<i class="fa fa-file-image-o"></i>
				</span>
				<ul class="sub-menu">
					<li class="">
						<a href="{{route('media')}}">Galeri</a>
						<span class="icon-thumbnail">G</span>
					</li>
					<li class="">
						<a href="{{route('media-files')}}">Dosya</a>
						<span class="icon-thumbnail">D</span>
					</li>
				</ul>
			</li>
			
			<li class="">
				<a href="{{route('menu')}}">
					<span class="title">Menü</span>
				</a>
				<span class="icon-thumbnail">
					<i class="fa fa-bars"></i>
				</span>
			</li>
			<li class="">
				<a href="{{route('settings')}}">
					<span class="title">Ayarlar</span>
				</a>
				<span class="icon-thumbnail">
					<i class="fa fa-cogs"></i>
				</span>
			</li>
		</ul>
		<div class="clearfix"></div>
	</div>
	<!-- END SIDEBAR MENU -->
</nav>
<!-- END SIDEBAR -->
<!-- END SIDEBPANEL-->