routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'as'      => 'home',
    'uses'    => 'site\SiteController@index'
]);


Route::group(['prefix' => 'manage', 'middleware' => 'role:superadministrator|administrator'], function () {
    Route::get('/', 'cms\AdminController@get_index')->name('site');
    Route::resource('/users', 'cms\UserController');
    Route::resource('/posts', 'cms\PostController');
    Route::resource('/pages', 'cms\PageController');    
    Route::resource('/contents', 'cms\ContentController');        
    Route::resource('/describing', 'cms\DescribingController');

    //CONTENS
    Route::resource('/banners', 'cms\BannerController');
    Route::resource('/brands', 'cms\BrandController');    
    Route::resource('/generic', 'cms\GenericController');
    Route::resource('/forum', 'cms\ForumController');
    Route::resource('/packets', 'cms\PacketController');    
    
    Route::get('/menu', 'cms\AdminController@getmenu')->name('menu');
    Route::post('/menu', 'cms\AdminController@postmenu');
    Route::get('/settings', 'cms\AdminController@get_settings')->name('settings');
    Route::post('/settings', 'cms\AdminController@post_settings');
    Route::post('/ajax', 'cms\AjaxController@post');
    Route::get('/media', function(){ return view('cms.media.index');})->name('media');
    Route::get('/media/files', function(){ return view('cms.media.files');})->name('media-files');

    // Other Link
    Route::get('posts/delete/{post_id}', ['uses' => 'cms\PostController@delete', 'as' => 'delete-post']);
    Route::get('banners/delete/{banner_id}', ['uses' => 'cms\BannerController@delete', 'as' => 'delete-banner']);
    Route::get('brands/delete/{brand_id}', ['uses' => 'cms\BrandController@delete', 'as' => 'delete-brand']);
    
    
    Route::get('/datatable/posts', ['uses' => 'cms\PostController@datatable', 'as' => 'posts.datatable']);
    Route::get('/datatable/banners', ['uses' => 'cms\BannerController@bannerDatatable', 'as' => 'banner.datatable']);
    Route::get('/datatable/brands', ['uses' => 'cms\BrandController@brandDatatable', 'as' => 'brand.datatable']);    
    Route::get('/datatable/generic', ['uses' => 'cms\GenericController@genericDatatable', 'as' => 'generic.datatable']);
    Route::get('/datatable/forum', ['uses' => 'cms\ForumController@forumDatatable', 'as' => 'forum.datatable']);
    Route::get('/datatable/packets', ['uses' => 'cms\PacketController@packetDatatable', 'as' => 'packet.datatable']);    

});
Auth::routes();


// Catch all page controller (place at the very bottom)
if (!Request::is('laravel-*') && !Request::is('photos/')){

    //Static Pages
    Route::get('forum', 'site\ForumController@index');
    Route::get('forum/{slug}', 'site\ForumController@show');    
    Route::get('iletisim', 'site\SiteController@contact');
    Route::get('blog', 'site\BlogController@index');
    Route::get('blog/{slug}', 'site\BlogController@show');
    Route::get('blog/{slug}/amp', 'site\BlogController@amp');
    Route::get('/sitemap', 'site\SitemapController@index');

    //Forms
    Route::get('form/{slug1}', 'site\FormController@index');

    Route::post('form', 'site\FormController@send')->name('form-send');

    //All Urls
    Route::get('{slug1}/{slug2?}/{slug3?}/{slug4?}', ['uses' => 'site\SiteController@getPage'])->where('slug', '([A-Za-z0-9\-\/]+)');
}

Route::get('/laravel-clear', function () {   
    echo "Cache temizlendi!";
});

app/Http/Controllers/cms/AdminController.php
<?php

namespace App\Http\Controllers\cms;

use Illuminate\Http\Request;
use App\Settings;
use App\Content;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Intervention\Image\Facades\Image;
use Storage;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Cache\Factory;
use Carbon;
use Auth;

class AdminController extends Controller
{
    public function get_index(){
        return view('cms.index');
    }

     public function get_settings(){
      $Settings=Settings::all();
      $s="";
      foreach($Settings as $Setting){
           $s[$Setting->keyword]=$Setting->value;
      }    
     
      return view('cms.settings')->with("Settings",$s);
        }
  
    public function post_settings(Request $request, Factory $cache){
            $Setting="";
            $cache->forget('settings');
           $Validator= Validator::make($request->all(), [
                'logo' => 'mimes:jpg,jpeg,png,gif',
            ]);

            if(isset($request->logo)){
              if($Validator->fails()){
                 return response(['status'=>'error','title'=>'Ayarlar','message'=>'Resim Yüklemede Sorun Oluştu.']);
              }   
              //$logo=Input::file('logo');
              //$uzanti=Input::file('logo')->getClientOriginalExtension();
              //$logo_isim='logo.'.$uzanti;
             // Storage::disk('uploads')->makeDirectory('img');
              //Image::make($logo->getRealPath())->resize(200,100)->save('uploads/img/'.$logo_isim);
              //  $request->logo="asd";
               
            }
           try{
                Settings::truncate();         
                unset($request['_token']);
                foreach ($request->all() as $key => $value){      
                    if($value) $Setting=Settings::create(['keyword'=>"$key",'value'=>"$value"]);        
                }
                 return response(['status'=>'success','title'=>'Ayarlar','message'=>'Başarıyla Kaydedildi.']);
           }
           catch(\Exception $e){               
                return response(['status'=>'error','title'=>'Ayarlar','message'=>'Bir Hata oluştu.']);
           }         
             
            
    }

    public function getmenu(){
        $menu = Content::where('type', 'menu')->pluck('content')->toArray();
     
        return view('cms.contents.menu.index')->with('menu',$menu[0]);
    }
    public function postmenu(Request $request, Factory $cache){
        $menu = Content::where('type', 'menu')->delete();
       
        $user=Auth::user()->id;
        $page=Content::create(['title'=>'HeaderMenu',
        'type'=>'menu',
        'content' => $request->json,
        'slug'=>'headermenu',
        'published_at' => Carbon\Carbon::now(),
        'created_at'=>Carbon\Carbon::now(),
        'user_id'=>$user,        
        'status'=>'published',
        'rank'=>0,
        'excerpt'=>'-',]);
       if($page){           
        $cache->forget('menu');
        return response(['status' => 'success', 'title' => 'Menü', 'message' => 'Başarıyla Kaydedildi.']);

       }
    }
}

app/Http/Controllers/cms/AjaxController.php
<?php

namespace App\Http\Controllers\cms;
use App\lib\Slug;
use App\Category;
use App\Post;
use App\Content;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AjaxController extends Controller
{
    public function post(Request $request){
        if ($request->process=="UrlSlug"){
            $slug = new Slug();
          
            $slug= $slug->createSlug($request->title,$request->lang,0,$request->type);
            return $slug;
        }
        if ($request->process=="getAltCategories"){
            $cat=Category::selectChild($request->id)->toArray();
            return $cat;
        }

        if ($request->process=="NewRowPosition"){
            $Model=$request->model;
            $posts = json_decode($request->ids);
            foreach ($posts as $p) {
                $post= $Model::findOrFail($p->id);
                $post->rank=$p->rank;
                $post->save();
            }
        }
        if($request->process=='getAltPages'){
            $page=Post::where('parent_id',$request->id)->with('children')->get();
            return $page;
        }

    }
}

app/Http/Controllers/cms/BannerController.php
<?php

namespace App\Http\Controllers\cms;

use App\Posts_Detail;
use Illuminate\Http\Request;
use Carbon;
use Datatables;
use App\Content;
use Auth;
use App\Contents_Detail;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Cache\Factory;

class BannerController extends Controller
{
   
    public function index()
    {
        return view('cms.contents.banners.index');
    }

    public function edit($id)
    { 
        $banner = Content::where('type', 'banner')->find($id);
        $category=Contents_Detail::where('content_id',$id)->pluck('value','key');        

        return view('cms.contents.banners.edit')->with('banner', $banner)->with('details',$category);
    }

    public function update(Request $request, $id, Factory $cache)
    {
       
        $a=$this->validate($request, [
            'title' => 'required|max:255',
            'detail.image' => 'required',
        ]);
        $banner = Content::findOrFail($id);
        $banner->slug = '';
        $banner->title = $request->title;
        $banner->excerpt = $request->excerpt;
        $banner->content = $request->content;
        $banner->status = $request->status;
        $banner->published_at = Carbon\Carbon::now();
        $banner->user_id = Auth::user()->id;

        if ($banner->save()) {
            Contents_Detail::where('content_id', $banner->id)->delete();

            foreach ($request->detail as $key => $value) {
                if ($value) {
                    $banner_detail = Contents_Detail::create(['content_id' => $banner->id, 'key' => "$key", 'value' => "$value"]);
                }
            }
            $cache->forget('banner');
            return response(['status' => 'success', 'title' => 'Banner', 'message' => 'Başarıyla Güncellendi.']);
        } else {
            return response(['status' => 'error', 'title' => 'Banner', 'message' => 'Bir hata oluştu']);
        }
    }
    public function create()
    {
        return view('cms.contents.banners.create');
    }
    public function store(Request $request, Factory $cache)
    {

        $this->validate($request, [
            'title' => 'required|max:255',
            'detail.image' => 'required',
        ]);

        $content = new Content();
        $last=Content::orderBy('created_at', 'desc')->take(1)->get();
        $last_id=$last[0]['id'];
      
        $request->request->add(['rank'=>$last_id+1, 'slug'=>'','user_id' => Auth::user()->id, 'published_at' => Carbon\Carbon::now()]);
        $content->fill($request->all());
        if ($content->save()) {
            foreach ($request->detail as $key => $value) {
                if ($value) {
                    $content_detail = Contents_Detail::create(['content_id' => $content->id, 'key' => "$key", 'value' => "$value"]);
                }
            }
            $redirecturl=route('banners.edit', ['post' => $content->id]);
            $cache->forget('banner');
            return response(['status' => 'success', 'title' => 'Banner', 'message' => 'Başarıyla Kaydedildi.', 'redirect' => $redirecturl]);
        } else {
            return response(['status' => 'error', 'title' => 'Banner', 'message' => 'Bir Hata oluştu.']);
        }
    }
    public function destroy($id)
    {
        $banner = Content::where('type', 'banner')->find($id);
        if ($banner->delete()) {
            $redirecturl=route('banners.index');
            return response(['status' => 'success', 'title' => 'Banner', 'message' => 'Başarıyla Silindi.', 'redirect' => $redirecturl ]);
        }
    }

    public function bannerDatatable()
    {
        $content = Content::select(['id', 'title', 'created_at', 'updated_at']);

        return Datatables::of(Content::query())
            ->addColumn('action', function ($content) {
                return '<a href="banners/' . $content->id . '/edit" class="btn btn-xs btn-primary pull-right"><i class="fa fa-edit"></i> Düzenle</a>';
            })
            ->editColumn('status', '{{__("cms.$status")}}')
            ->where('type', 'banner')            
            ->orderby('status', 'desc')
            ->orderby('rank', 'desc')
            ->make(true);
    }
}

app/Http/Controllers/cms/BrandController.php
<?php

namespace App\Http\Controllers\cms;

use App\Posts_Detail;
use Illuminate\Http\Request;
use Carbon;
use Datatables;
use App\Content;
use Auth;
use App\Contents_Detail;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Cache\Factory;

class BrandController extends Controller
{
   
    public function index()
    {
        return view('cms.contents.brands.index');
    }

    public function edit($id)
    { 
        $banner = Content::where('type', 'brand')->find($id);
        $category=Contents_Detail::where('content_id',$id)->pluck('value','key');  
        return view('cms.contents.brands.edit')->with('brand', $banner)->with('details',$category);

    }

    public function update(Request $request, $id, Factory $cache)
    {
       
        $a=$this->validate($request, [
            'title' => 'required|max:255',
            'detail.image' => 'required',
        ]);
        $brand = Content::findOrFail($id);
        $brand->slug = '';
        $brand->title = $request->title;
        $brand->excerpt = $request->excerpt;
        $brand->content = $request->content;
        $brand->status = $request->status;
        $brand->published_at = Carbon\Carbon::now();
        $brand->user_id = Auth::user()->id;

        if ($brand->save()) {
            Contents_Detail::where('content_id', $brand->id)->delete();

            foreach ($request->detail as $key => $value) {
                if ($value) {
                    $brand_detail = Contents_Detail::create(['content_id' => $brand->id, 'key' => "$key", 'value' => "$value"]);
                }
            }
            $cache->forget('brand');
            return response(['status' => 'success', 'title' => 'Şirket', 'message' => 'Başarıyla Güncellendi.']);
        } else {
            return response(['status' => 'error', 'title' => 'Şirket', 'message' => 'Bir hata oluştu']);
        }
    }
    public function create()
    {
        return view('cms.contents.brands.create');
    }
    public function store(Request $request, Factory $cache)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'detail.image' => 'required',
        ]);

        $content = new Content();
        $last=Content::orderBy('created_at', 'desc')->take(1)->get();
        $last_id=$last[0]['id'];
      
        $request->request->add(['rank'=>$last_id+1, 'slug'=>'','user_id' => Auth::user()->id, 'published_at' => Carbon\Carbon::now()]);
        $content->fill($request->all());
        if ($content->save()) {
            foreach ($request->detail as $key => $value) {
                if ($value) {
                    $content_detail = Contents_Detail::create(['content_id' => $content->id, 'key' => "$key", 'value' => "$value"]);
                }
            }
            $redirecturl=route('brands.edit', ['post' => $content->id]);
            $cache->forget('brand');
            return response(['status' => 'success', 'title' => 'Şirket', 'message' => 'Başarıyla Kaydedildi.', 'redirect' => $redirecturl]);
        } else {
            return response(['status' => 'error', 'title' => 'Şirket', 'message' => 'Bir Hata oluştu.']);
        }
    }
    public function destroy($id)
    {
        $forum = Content::where('type', 'brand')->find($id);
        if ($forum->delete()) {
            $redirecturl=route('brands.index');
            return response(['status' => 'success', 'title' => 'Şirket içeriği', 'message' => 'Başarıyla Silindi.', 'redirect' => $redirecturl ]);
        }
    }
    public function brandDatatable()
    {
        $content = Content::select(['id', 'title', 'created_at', 'updated_at']);
        return Datatables::of(Content::query())
            ->addColumn('action', function ($content) {
                return '<a href="brands/' . $content->id . '/edit" class="btn btn-xs btn-primary pull-right"><i class="fa fa-edit"></i> Düzenle</a>';
            })
            ->editColumn('status', '{{__("cms.$status")}}')
            ->where('type', 'brand')            
            ->orderby('status', 'desc')
            ->orderby('rank', 'desc')
            ->make(true);
    }
}

app/Http/Controllers/cms/ContentController.php
<?php

namespace App\Http\Controllers\cms;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Content;
use Datatables;

class ContentController extends Controller
{
    public function index(){
        return view('cms.contents.index');
    }
    public function create(){
        $content=Content::where('parent_id','0')->pluck('title','id');
        $content=collect(['' => 'Seçiniz'] + $category->all());
        
        return view('cms.contents.create')->with('content',$content);
    }

    public function bannerIndex(){
        return view('cms.contents.banners.index');
    }






}

resources/views/cms/describing/create.blade.php
@extends('cms.app') @section('title') Yeni Kategori Ekle @endsection @section('content')
	<div class="content sm-gutter">
		<!-- START CONTAINER FLUID -->
		<div class="jumbotron" data-pages="parallax">
			<div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
				<div class="inner" style="transform: translateY(0px); opacity: 1;">
				<h4 class="page-title">@yield('title')</h4>
				</div>
			</div>
		</div>
		<div class="container-fluid container-fixed-lg">
			<div class="">				
				<form data-js="slug" method="post" action="{{route('describing.store')}}" id="form" enctype="multipart/form-data">
					{{csrf_field()}}
					<input type="hidden" name="lang" value="tr">
					<div class="col-sm-9 no-padding">
						<div class="panel panel-default">
							<div class="panel-body">
								<div class="form-group form-group-default form-group-default-select2 required">
									<label class="">Kategori Tipi</label>
									{!! Form::select('items', $categories, null,array('class' => 'CategoryType full-width required','data-init-plugin'=>'select2',"data-disable-search"=>"true") ) !!}
								</div>

								<div class="form-group form-group-default form-group-default-select2 required">
									<label class="">Üst Kategori</label>
									{!! Form::select('item',array(''=>''), null,array('class' => 'Category full-width required','data-init-plugin'=>'select2',"data-disable-search"=>"true",'name'=>'parent_id') ) !!}
								</div>

								<div class="form-group form-group-default required ">
									<label>Başlık</label>
									<input type="text" class="form-control" name="title" required>
								</div>
								<div class="form-group form-group-default required ">
									<label>Url</label>
									<input type="text" class="form-control" name="slug" required>
								</div>

								<div class="form-group form-group-default">
									<label>Açıklama</label>
									<textarea style="min-height:90px" rows="10" cols="10" class="form-control" name="description" required></textarea>
								</div>

								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>Etiket</label>
										<input class="tagsinput custom-tag-input" type="text" name="key" value="hello World, quotes, inspiration" />
									</div>
								</div>

							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="row">
							<div class="card share">
								<div class="card-description">
									<button class="btn btn-primary pull-right col-sm-12 col-md-5" name="status"
									        value="2"
									        type="submit">Ekle
									</button>
								</div>

							</div>
						</div>
					</div>

				</form>

			</div>
		</div>
	</div>
	</div>
@endsection
@section('js')
	<script src="/cms/js/form.js"></script>
	<script>
				{!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/lfm.js')) !!}
        var route_prefix = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";
        $('#lfm').filemanager('image', {prefix: route_prefix});

        $('.CategoryType').trigger('change');

	</script>
@endsection

resources/views/cms/describing/edit.blade.php
@extends('cms.app') 
@section('title') Kategori Düzenle @endsection
@section('content')
	content
@endsection
@section('css')
@endsection
@section('js')
@endsection

resources/views/cms/describing/index.blade.php
@extends('cms.app')
@section('title') Tanımlamalar @endsection
@section('secondnav')<a href="#" class="toggle-secondary-sidebar">Kategoriler<span class="text-info"></span> <span class="caret"></span></a>@endsection
@section('content')
	<div class="content full-height">
		<nav class="secondary-sidebar padding-30">
			<a href="{{route('describing.create')}}" class="btn btn-complete btn-block btn-compose m-b-30">Yeni Ekle</a>
			<ul class="main-menu">
				@foreach($categories as $category)
				<li class="">
					<a class="getAltCategories" data-id="{{$category->id}}" href="#">
						<span class="title"><i class=""></i>{{$category->title}}</span>
					</a>
				</li>
					@endforeach
			</ul>
		</nav>
		<div class="inner-content full-height">
				<div class="panel-heading" style="overflow:hidden">
					<h4 class="page-title pull-left">@yield('title')</h4>

				</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-striped">
							<thead>
							<tr>
								<th>Başlık</th>
								<th>Actions</th>
							</tr>
							</thead>
							<tbody class="getdata">


							</tbody>
						</table>
					</div>
					{{--{{$posts->links()}}--}}
				</div>
		</div>
	</div>
@endsection
@section('css')
@endsection

@section('js')
	<script>
	$('.toggle-secondary-sidebar').click(function(e) {
	e.stopPropagation();
	$('.secondary-sidebar').toggle();
	});
    $(window).resize(function() {

        if ($(window).width() <= 1024) {
            $('.secondary-sidebar').hide();

        } else {
            $('.secondary-sidebar').show();
        }
    });
	</script>
@endsection

resources/views/cms/describing/show.blade.php
@extends('cms.app') 
@section('title')  Kategori Detay @endsection
@section('content')
	content
@endsection
@section('css')
@endsection
@section('js')
@endsection