routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'as'      => 'home',
    'uses'    => 'site\SiteController@index'
]);


Route::group(['prefix' => 'manage', 'middleware' => 'role:superadministrator|administrator'], function () {
    Route::get('/', 'cms\AdminController@get_index')->name('site');
    Route::resource('/users', 'cms\UserController');
    Route::resource('/posts', 'cms\PostController');
    Route::resource('/pages', 'cms\PageController');    
    Route::resource('/contents', 'cms\ContentController');        
    Route::resource('/describing', 'cms\DescribingController');

    //CONTENS
    Route::resource('/banners', 'cms\BannerController');
    Route::resource('/brands', 'cms\BrandController');    
    Route::resource('/generic', 'cms\GenericController');
    Route::resource('/forum', 'cms\ForumController');
    Route::resource('/packets', 'cms\PacketController');    
    
    Route::get('/menu', 'cms\AdminController@getmenu')->name('menu');
    Route::post('/menu', 'cms\AdminController@postmenu');
    Route::get('/settings', 'cms\AdminController@get_settings')->name('settings');
    Route::post('/settings', 'cms\AdminController@post_settings');
    Route::post('/ajax', 'cms\AjaxController@post');
    Route::get('/media', function(){ return view('cms.media.index');})->name('media');
    Route::get('/media/files', function(){ return view('cms.media.files');})->name('media-files');

    // Other Link
    Route::get('posts/delete/{post_id}', ['uses' => 'cms\PostController@delete', 'as' => 'delete-post']);
    Route::get('banners/delete/{banner_id}', ['uses' => 'cms\BannerController@delete', 'as' => 'delete-banner']);
    Route::get('brands/delete/{brand_id}', ['uses' => 'cms\BrandController@delete', 'as' => 'delete-brand']);
    
    
    Route::get('/datatable/posts', ['uses' => 'cms\PostController@datatable', 'as' => 'posts.datatable']);
    Route::get('/datatable/banners', ['uses' => 'cms\BannerController@bannerDatatable', 'as' => 'banner.datatable']);
    Route::get('/datatable/brands', ['uses' => 'cms\BrandController@brandDatatable', 'as' => 'brand.datatable']);    
    Route::get('/datatable/generic', ['uses' => 'cms\GenericController@genericDatatable', 'as' => 'generic.datatable']);
    Route::get('/datatable/forum', ['uses' => 'cms\ForumController@forumDatatable', 'as' => 'forum.datatable']);
    Route::get('/datatable/packets', ['uses' => 'cms\PacketController@packetDatatable', 'as' => 'packet.datatable']);    

});
Auth::routes();


// Catch all page controller (place at the very bottom)
if (!Request::is('laravel-*') && !Request::is('photos/')){

    //Static Pages
    Route::get('forum', 'site\ForumController@index');
    Route::get('forum/{slug}', 'site\ForumController@show');    
    Route::get('iletisim', 'site\SiteController@contact');
    Route::get('blog', 'site\BlogController@index');
    Route::get('blog/{slug}', 'site\BlogController@show');
    Route::get('blog/{slug}/amp', 'site\BlogController@amp');
    Route::get('/sitemap', 'site\SitemapController@index');

    //Forms
    Route::get('form/{slug1}', 'site\FormController@index');

    Route::post('form', 'site\FormController@send')->name('form-send');

    //All Urls
    Route::get('{slug1}/{slug2?}/{slug3?}/{slug4?}', ['uses' => 'site\SiteController@getPage'])->where('slug', '([A-Za-z0-9\-\/]+)');
}

Route::get('/laravel-clear', function () {   
    echo "Cache temizlendi!";
});

app/Http/Controllers/cms/AdminController.php
<?php

namespace App\Http\Controllers\cms;

use Illuminate\Http\Request;
use App\Settings;
use App\Content;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Intervention\Image\Facades\Image;
use Storage;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Cache\Factory;
use Carbon;
use Auth;

class AdminController extends Controller
{
    public function get_index(){
        return view('cms.index');
    }

     public function get_settings(){
      $Settings=Settings::all();
      $s="";
      foreach($Settings as $Setting){
           $s[$Setting->keyword]=$Setting->value;
      }    
     
      return view('cms.settings')->with("Settings",$s);
        }
  
    public function post_settings(Request $request, Factory $cache){
            $Setting="";
            $cache->forget('settings');
           $Validator= Validator::make($request->all(), [
                'logo' => 'mimes:jpg,jpeg,png,gif',
            ]);

            if(isset($request->logo)){
              if($Validator->fails()){
                 return response(['status'=>'error','title'=>'Ayarlar','message'=>'Resim Yüklemede Sorun Oluştu.']);
              }   
              //$logo=Input::file('logo');
              //$uzanti=Input::file('logo')->getClientOriginalExtension();
              //$logo_isim='logo.'.$uzanti;
             // Storage::disk('uploads')->makeDirectory('img');
              //Image::make($logo->getRealPath())->resize(200,100)->save('uploads/img/'.$logo_isim);
              //  $request->logo="asd";
               
            }
           try{
                Settings::truncate();         
                unset($request['_token']);
                foreach ($request->all() as $key => $value){      
                    if($value) $Setting=Settings::create(['keyword'=>"$key",'value'=>"$value"]);        
                }
                 return response(['status'=>'success','title'=>'Ayarlar','message'=>'Başarıyla Kaydedildi.']);
           }
           catch(\Exception $e){               
                return response(['status'=>'error','title'=>'Ayarlar','message'=>'Bir Hata oluştu.']);
           }         
             
            
    }

    public function getmenu(){
        $menu = Content::where('type', 'menu')->pluck('content')->toArray();
     
        return view('cms.contents.menu.index')->with('menu',$menu[0]);
    }
    public function postmenu(Request $request, Factory $cache){
        $menu = Content::where('type', 'menu')->delete();
       
        $user=Auth::user()->id;
        $page=Content::create(['title'=>'HeaderMenu',
        'type'=>'menu',
        'content' => $request->json,
        'slug'=>'headermenu',
        'published_at' => Carbon\Carbon::now(),
        'created_at'=>Carbon\Carbon::now(),
        'user_id'=>$user,        
        'status'=>'published',
        'rank'=>0,
        'excerpt'=>'-',]);
       if($page){           
        $cache->forget('menu');
        return response(['status' => 'success', 'title' => 'Menü', 'message' => 'Başarıyla Kaydedildi.']);

       }
    }
}

app/Http/Controllers/cms/AjaxController.php
<?php

namespace App\Http\Controllers\cms;
use App\lib\Slug;
use App\Category;
use App\Post;
use App\Content;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AjaxController extends Controller
{
    public function post(Request $request){
        if ($request->process=="UrlSlug"){
            $slug = new Slug();
          
            $slug= $slug->createSlug($request->title,$request->lang,0,$request->type);
            return $slug;
        }
        if ($request->process=="getAltCategories"){
            $cat=Category::selectChild($request->id)->toArray();
            return $cat;
        }

        if ($request->process=="NewRowPosition"){
            $Model=$request->model;
            $posts = json_decode($request->ids);
            foreach ($posts as $p) {
                $post= $Model::findOrFail($p->id);
                $post->rank=$p->rank;
                $post->save();
            }
        }
        if($request->process=='getAltPages'){
            $page=Post::where('parent_id',$request->id)->with('children')->get();
            return $page;
        }

    }
}

app/Http/Controllers/cms/BannerController.php
<?php

namespace App\Http\Controllers\cms;

use App\Posts_Detail;
use Illuminate\Http\Request;
use Carbon;
use Datatables;
use App\Content;
use Auth;
use App\Contents_Detail;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Cache\Factory;

class BannerController extends Controller
{
   
    public function index()
    {
        return view('cms.contents.banners.index');
    }

    public function edit($id)
    { 
        $banner = Content::where('type', 'banner')->find($id);
        $category=Contents_Detail::where('content_id',$id)->pluck('value','key');        

        return view('cms.contents.banners.edit')->with('banner', $banner)->with('details',$category);
    }

    public function update(Request $request, $id, Factory $cache)
    {
       
        $a=$this->validate($request, [
            'title' => 'required|max:255',
            'detail.image' => 'required',
        ]);
        $banner = Content::findOrFail($id);
        $banner->slug = '';
        $banner->title = $request->title;
        $banner->excerpt = $request->excerpt;
        $banner->content = $request->content;
        $banner->status = $request->status;
        $banner->published_at = Carbon\Carbon::now();
        $banner->user_id = Auth::user()->id;

        if ($banner->save()) {
            Contents_Detail::where('content_id', $banner->id)->delete();

            foreach ($request->detail as $key => $value) {
                if ($value) {
                    $banner_detail = Contents_Detail::create(['content_id' => $banner->id, 'key' => "$key", 'value' => "$value"]);
                }
            }
            $cache->forget('banner');
            return response(['status' => 'success', 'title' => 'Banner', 'message' => 'Başarıyla Güncellendi.']);
        } else {
            return response(['status' => 'error', 'title' => 'Banner', 'message' => 'Bir hata oluştu']);
        }
    }
    public function create()
    {
        return view('cms.contents.banners.create');
    }
    public function store(Request $request, Factory $cache)
    {

        $this->validate($request, [
            'title' => 'required|max:255',
            'detail.image' => 'required',
        ]);

        $content = new Content();
        $last=Content::orderBy('created_at', 'desc')->take(1)->get();
        $last_id=$last[0]['id'];
      
        $request->request->add(['rank'=>$last_id+1, 'slug'=>'','user_id' => Auth::user()->id, 'published_at' => Carbon\Carbon::now()]);
        $content->fill($request->all());
        if ($content->save()) {
            foreach ($request->detail as $key => $value) {
                if ($value) {
                    $content_detail = Contents_Detail::create(['content_id' => $content->id, 'key' => "$key", 'value' => "$value"]);
                }
            }
            $redirecturl=route('banners.edit', ['post' => $content->id]);
            $cache->forget('banner');
            return response(['status' => 'success', 'title' => 'Banner', 'message' => 'Başarıyla Kaydedildi.', 'redirect' => $redirecturl]);
        } else {
            return response(['status' => 'error', 'title' => 'Banner', 'message' => 'Bir Hata oluştu.']);
        }
    }
    public function destroy($id)
    {
        $banner = Content::where('type', 'banner')->find($id);
        if ($banner->delete()) {
            $redirecturl=route('banners.index');
            return response(['status' => 'success', 'title' => 'Banner', 'message' => 'Başarıyla Silindi.', 'redirect' => $redirecturl ]);
        }
    }

    public function bannerDatatable()
    {
        $content = Content::select(['id', 'title', 'created_at', 'updated_at']);

        return Datatables::of(Content::query())
            ->addColumn('action', function ($content) {
                return '<a href="banners/' . $content->id . '/edit" class="btn btn-xs btn-primary pull-right"><i class="fa fa-edit"></i> Düzenle</a>';
            })
            ->editColumn('status', '{{__("cms.$status")}}')
            ->where('type', 'banner')            
            ->orderby('status', 'desc')
            ->orderby('rank', 'desc')
            ->make(true);
    }
}

app/Http/Controllers/cms/BrandController.php
<?php

namespace App\Http\Controllers\cms;

use App\Posts_Detail;
use Illuminate\Http\Request;
use Carbon;
use Datatables;
use App\Content;
use Auth;
use App\Contents_Detail;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Cache\Factory;

class BrandController extends Controller
{
   
    public function index()
    {
        return view('cms.contents.brands.index');
    }

    public function edit($id)
    { 
        $banner = Content::where('type', 'brand')->find($id);
        $category=Contents_Detail::where('content_id',$id)->pluck('value','key');  
        return view('cms.contents.brands.edit')->with('brand', $banner)->with('details',$category);

    }

    public function update(Request $request, $id, Factory $cache)
    {
       
        $a=$this->validate($request, [
            'title' => 'required|max:255',
            'detail.image' => 'required',
        ]);
        $brand = Content::findOrFail($id);
        $brand->slug = '';
        $brand->title = $request->title;
        $brand->excerpt = $request->excerpt;
        $brand->content = $request->content;
        $brand->status = $request->status;
        $brand->published_at = Carbon\Carbon::now();
        $brand->user_id = Auth::user()->id;

        if ($brand->save()) {
            Contents_Detail::where('content_id', $brand->id)->delete();

            foreach ($request->detail as $key => $value) {
                if ($value) {
                    $brand_detail = Contents_Detail::create(['content_id' => $brand->id, 'key' => "$key", 'value' => "$value"]);
                }
            }
            $cache->forget('brand');
            return response(['status' => 'success', 'title' => 'Şirket', 'message' => 'Başarıyla Güncellendi.']);
        } else {
            return response(['status' => 'error', 'title' => 'Şirket', 'message' => 'Bir hata oluştu']);
        }
    }
    public function create()
    {
        return view('cms.contents.brands.create');
    }
    public function store(Request $request, Factory $cache)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'detail.image' => 'required',
        ]);

        $content = new Content();
        $last=Content::orderBy('created_at', 'desc')->take(1)->get();
        $last_id=$last[0]['id'];
      
        $request->request->add(['rank'=>$last_id+1, 'slug'=>'','user_id' => Auth::user()->id, 'published_at' => Carbon\Carbon::now()]);
        $content->fill($request->all());
        if ($content->save()) {
            foreach ($request->detail as $key => $value) {
                if ($value) {
                    $content_detail = Contents_Detail::create(['content_id' => $content->id, 'key' => "$key", 'value' => "$value"]);
                }
            }
            $redirecturl=route('brands.edit', ['post' => $content->id]);
            $cache->forget('brand');
            return response(['status' => 'success', 'title' => 'Şirket', 'message' => 'Başarıyla Kaydedildi.', 'redirect' => $redirecturl]);
        } else {
            return response(['status' => 'error', 'title' => 'Şirket', 'message' => 'Bir Hata oluştu.']);
        }
    }
    public function destroy($id)
    {
        $forum = Content::where('type', 'brand')->find($id);
        if ($forum->delete()) {
            $redirecturl=route('brands.index');
            return response(['status' => 'success', 'title' => 'Şirket içeriği', 'message' => 'Başarıyla Silindi.', 'redirect' => $redirecturl ]);
        }
    }
    public function brandDatatable()
    {
        $content = Content::select(['id', 'title', 'created_at', 'updated_at']);
        return Datatables::of(Content::query())
            ->addColumn('action', function ($content) {
                return '<a href="brands/' . $content->id . '/edit" class="btn btn-xs btn-primary pull-right"><i class="fa fa-edit"></i> Düzenle</a>';
            })
            ->editColumn('status', '{{__("cms.$status")}}')
            ->where('type', 'brand')            
            ->orderby('status', 'desc')
            ->orderby('rank', 'desc')
            ->make(true);
    }
}

app/Http/Controllers/cms/ContentController.php
<?php

namespace App\Http\Controllers\cms;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Content;
use Datatables;

class ContentController extends Controller
{
    public function index(){
        return view('cms.contents.index');
    }
    public function create(){
        $content=Content::where('parent_id','0')->pluck('title','id');
        $content=collect(['' => 'Seçiniz'] + $category->all());
        
        return view('cms.contents.create')->with('content',$content);
    }

    public function bannerIndex(){
        return view('cms.contents.banners.index');
    }






}

resources/views/cms/pages/create.blade.php
@extends('cms.app') @section('title') Sayfa Yazı Ekle @endsection @section('content')
<div class="content sm-gutter">
	<!-- START CONTAINER FLUID -->
	<div class="jumbotron" data-pages="parallax">
		<div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
			<div class="inner" style="transform: translateY(0px); opacity: 1;">
				<h4 class="page-title">@yield('title')</h4>
			</div>
		</div>
	</div>
	<div class="container-fluid container-fixed-lg">
		<div class="row">
			<form data-js="slug summernote" method="post" action="{{route('pages.store')}}" id="form" enctype="multipart/form-data">
				{{csrf_field()}}
				<input type="hidden" name="lang" value="tr">
				<input type="hidden" name="type" value="page">
				<input type="hidden" name="parent_id" value="<?=$_GET['parentid'];?>">
				<div class="col-sm-9 no-padding">
					<ul class="nav  nav-tabs nav-tabs-fillup">
						<li class="active">
							<a data-toggle="tab" href="#slide1">
								<span>Genel</span>
							</a>
						</li>
						<li>
							<a data-toggle="tab" href="#slide2">
								<span>Seo</span>
							</a>
						</li>					
					</ul>
					<div class="tab-content">
						<div class="tab-pane active" id="slide1">
							<div class="row column-seperation">
								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>Başlık</label>
										<input type="text" class="form-control required" name="title" required>
									</div>
								</div>
								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>{{ config('settings.siteurl') }}</label>
										<input tabindex="-1" type="text" class="form-control required" name="slug" placeholder="" required>
									</div>
								</div>

								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>Özet</label>
										<textarea style="min-height:90px" rows="10" cols="10" class="form-control required" name="excerpt" required> </textarea>
									</div>
								</div>							
								
								<div class="col-sm-12">
										<div class="form-group form-group-default required">
									<h5>İçerik</h5>
									<div class="summernote-wrapper">
										<textarea id="summernote-editor" class="required" name="content" required></textarea>
									</div>
									</div>
								</div>
								
							</div>
						</div>
						<div class="tab-pane slide-left" id="slide2">
							<div class="row column-seperation">
								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>Meta Title</label>
										<input type="text" class="form-control" name="detail[metatit]">
									</div>
								</div>
								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>Meta Key</label>
										<input type="text" class="form-control" name="detail[metakey]">
									</div>
								</div>
								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>Meta Description</label>
										<input type="text" class="form-control" name="detail[metadesc]">
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-3 m-t-50 sm-m-t-0">
					<div class="row">

						<div class="card share">
							<div class="card-description">

								<button class="btn btn-warning pull-left col-sm-12 col-md-5 m-b-10" name="status" value="draft" type="submit">Taslak
								</button>
								<button class="btn btn-primary pull-right col-sm-12 col-md-5" name="status" value="published" type="submit">Yayınla
								</button>
							</div>

						</div>
					</div>
				</div>

			</form>

		</div>
	</div>
</div>
</div>
@endsection 
@section('js')
<script src="/cms/js/form.js"></script>

<script>
		
	{!!\File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/lfm.js')) !!}
	var route_prefix = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";
	$('#lfm').filemanager('image', {
		prefix: route_prefix
	});
	$(function(){
		
		$.get("/api/category/1", function (data) {
			if (data.length > 0) {
				var compiled = _.template(
					'<% _.forEach(categories, function(category) { %><option value="<%- category.id %>"><%- category.title %></option><% }); %>'
				);
				$("select.Category").empty().trigger("select2.change");
				$('select.Category').append(compiled({
					'categories': data
				})).trigger('change');
	
			}
		})
	})
</script>
@endsection

resources/views/cms/pages/edit.blade.php
@extends('cms.app') 
@section('title') Sayfa Düzenle
@endsection
 
@section('content')
<div class="content sm-gutter">
	<!-- START CONTAINER FLUID -->
	<div class="jumbotron" data-pages="parallax">
		<div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
			<div class="inner" style="transform: translateY(0px); opacity: 1;">
				<h4 class="page-title">@yield('title')</h4>
			</div>
		</div>
	</div>
	<div class="container-fluid container-fixed-lg">
		<div class="row">
			<form data-js="slug summernote" action="{{route('pages.update',$post->id)}}" method="POST" id="form" enctype="multipart/form-data">
				{{ csrf_field() }} {{ method_field('PATCH') }}
				<div class="col-sm-8 col-md-9 no-padding">
					@if ($errors->any())
					<div class="alert alert-danger">
						<ul>
							@foreach ($errors->all() as $error)
							<li>{{ $error }}</li>
							@endforeach
						</ul>
					</div>
					@endif
					<ul class="nav  nav-tabs nav-tabs-fillup" data-init-reponsive-tabs="dropdownfx">
						<li class="active">
							<a data-toggle="tab" href="#slide1">
						<span>Genel</span>
					</a>
						</li>
						<li>
							<a data-toggle="tab" href="#slide2">
						<span>Seo</span>
					</a>
						</li>
					</ul>
					<div class="tab-content">
						<div class="tab-pane  active" id="slide1">
							<div class="row column-seperation">
								<div class="col-sm-6">
									<div class="form-group form-group-default required">
										<label>Başlık</label>
										<input type="text" class="form-control" name="title" required value="{{$post->title}}">
									</div>
								</div>
								<div class="col-sm-6">
									<div class="form-group form-group-default input-group">
										<span class="input-group-addon">
                                http://laravel.bob/
                            </span>
										<label>Url</label>
										<input type="text" class="form-control" name="slug" placeholder="" required value="{{$post->slug}}">
									</div>
								</div>
								<div class="col-sm-12">
									<div class="form-group form-group-default">
										<label>Özet</label>
										<textarea style="min-height:90px" rows="10" cols="10" class="form-control" name="excerpt">{{$post->excerpt}}</textarea>
									</div>
								</div>
								<div class="col-sm-12">
									<h5>İçerik</h5>
									<div class="summernote-wrapper">
										<textarea id="summernote-editor" name="content">{{$post->content}}</textarea>
									</div>
								</div>
							</div>
						</div>
						<div class="tab-pane slide-left" id="slide2">
							<div class="row column-seperation">
								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>Meta Title</label>
										<input type="text" class="form-control" name="detail[metatit]" value="@isset($details['metatit']){{$details['metatit']}} @endisset">
									</div>
								</div>
								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>Meta Key</label>
										<input type="text" class="form-control" name="detail[metakey]" value="@isset($details['metakey']){{$details['metakey']}} @endisset">
									</div>
								</div>
								<div class="col-sm-12">
									<div class="form-group form-group-default required">
										<label>Meta Description</label>
										<input type="text" class="form-control" name="detail[metadesc]" value="@isset($details['metadesc']){{$details['metadesc']}} @endisset">
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-4 col-md-3">
					<div class="row">
						<div class="card share">
							<div class="card-header clearfix">
								<div class="user-pic">
									<img alt="Profile Image" width="33" height="33" data-src-retina="/cms/img/profiles/avatar.jpg" data-src="/cms/img/profiles/avatar.jpg"
									 src="/cms/img/profiles/avatar.jpg">
								</div>
								<h5>{{$post->user->name}}</h5>
								<h6>{{__('cms.'.$post->status)}}
									<span class="location semi-bold">
								<i class="fa fa-clock-o"></i> {{$post->published_at}}</span>
								</h6>
							</div>
							<div class="card-description">
								<a class="delete-btn btn btn-danger pull-left" style="margin-right:10px;" href="{{ URL::route('pages.destroy',$post->id) }}">Sil</a>
								<button class="btn btn-warning pull-left" type="submit" name="status" value="draft">Taslak</button>
								<button type="submit" class="btn btn-primary pull-right" name="status" value="published">Düzenle</button>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
</div>
@endsection
 
@section('css') 
@section('js')
<script src="/cms/js/form.js"></script>
<script>
	{!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/lfm.js')) !!}
        var route_prefix = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";
		$('#lfm').filemanager('image', {prefix: route_prefix});
		
		$(function(){
		
			$.get("/api/category/1", function (data) {
				if (data.length > 0) {
					var compiled = _.template(
						'<% _.forEach(categories, function(category) { %><option value="<%- category.id %>"><%- category.title %></option><% }); %>'
					);
					$("select.Category").empty().trigger("select2.change");
					$('select.Category').append(compiled({
						'categories': data
					})).trigger('change');
					$selected_id=$("input[name='cat-id']").val();					;
					$('select.Category').select2('val',$selected_id).trigger('change');
				}
			})
		})
</script>
@endsection

resources/views/cms/pages/index.blade.php
@extends('cms.app')
@section('title') Sayfalar @endsection

@section('content')
	<div class="content sm-gutter">

		<div class="container-fluid container-fixed-lg bg-white">
			<!-- START PANEL -->
			<div class="panel panel-transparent">
				<div class="panel-heading">
					<div class="panel-title">@yield('title')
					</div>									
				</div>
				<div class="panel-body">
					<div class="pagelist col-lg-3 col-md-4 col-sm-4 col-xs-12 first">
					<div class="pagelist-header">
						<a class="pull-left addPage" data-id="0" href="/manage/pages/create?parentid=0&crm=2q90rmc2r294352v90mtu029cm924u93"><i class="fa fa-plus"></i></a>
						<h4>Anasayfa</h4>
					</div>
						<ul>
							@foreach($page as $p)
							<li><span class="link context-menu" data-id="{{$p->id}}"><i class="fa {{$p->status}}"></i>{{$p->title}}</span>
							<a href="/manage/pages/{{$p->id}}/edit" title="Düzenle"><i class="fa fa-pencil"></i></a>
							@endforeach
						</ul>
					</div>
					<div class="other"></div>
					
				</div>
				
			</div>
			<!-- END PANEL -->
		</div>
		<!-- START CONTAINER FLUID -->
	</div>

@endsection
@section('css')

@endsection

@section('js')
<script type="text/template" id="pagelist-Template">
	<div class="pagelist col-lg-3 col-md-4 col-sm-4 col-xs-12">
		<div class="pagelist-header">
			<a class="pull-left addPage" data-id="0" href="#"><i class="fa fa-plus"></i></a>
			<h4 class="title">Anasayfa</h4>
		</div>
		<ul>
		<% _.forEach(pages, function(page) { %>
		<li>
			<span class="link context-menu" data-id="<%- page.id %>"><i class="fa <%- page.status %>"></i> <%- page.title %></span>
			<a href="/manage/pages/<%- page.id %>/edit" title="Düzenle"><i class="fa fa-pencil"></i></a>
		</li>
		<% }); %>
		</ul>
	</div>
</script>


@endsection